name: spin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - mkl
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - networkx
  - pandas
  - matplotlib
  - seaborn
  - sqlite
  - libopus
  - ffmpeg
  - alsa-lib
  - cairo
  - fontconfig
  - freetype
  - harfbuzz
  - icu
  - libglib
  - openssl
  - zlib
  - pip:
      - bertopic==0.17.4
      - sentence-transformers==5.2.0
      - transformers==4.57.3
      - spacy==3.8.11
      - streamlit==1.52.2
      - plotly==6.5.0
      - pyvis==0.3.2
      - hdbscan==0.8.40
      - umap-learn==0.5.7
      - wordcloud==1.9.4
      - fugashi==1.5.2
      - ipython==8.37.0
      - tqdm==4.67.1
      - pydantic==2.12.5
      - requests==2.32.5