version: '3.11'
services:
  streamlit:
    build: ./
    container_name: bsky-analysis-research-app
    ports:
      - 8502:8502
    command: streamlit run app.py --server.port=8502 --server.address=0.0.0.0
    volumes:
      - ./:/app

volumes:
  esdata:
